.TH ECHO 1 "May 2020" "samedamci's coreutils" "User Commands"
.SH NAME
echo \- display a line of text
.SH SYNOPSIS
.B echo
.RI [ OPTION ]...
.RI [ STRING ]
.SH DESCRIPTION
Echo the STRING to standard output.
.SH OPTIONS
.TP
\fB\-n
do not output the trailing newline
.TP
\fB\-e
enable interpretation of backslash escapes
.TP
\fB\-E
disable interpretation of backslash escapes (default)
.TP
\fB\-\-help
display help and exit
.TP
\fB\-\-version
output version information and exit
.SH ESCAPES
If \fB-e\fR is in effect, the following sequences are recognized:
.TP
\\\\
backslash
.TP
\\a
alert (BEL)
.TP
\\b
backspace
.TP
\\c
produce no further output
.TP
\\e
escape
.TP
\\f
form feed

.TP
\\n
new line
.TP
\\r
carriage return
.TP
\\t
horizontal tab
.TP
\\v
vertical tab
.SH AUTHOR
Implementation of echo written by samedamci.
.SH REPORTING BUGS
Report bugs to <https://github.com/samedamci/core_utils>
.SH LICENSE
License ISC 2020.
